### ISSUE TITLE
Sample Implementation links 404  on OpenVG Registry page

### ISSUE THREAD

**Issue by KhronosWebservices** [KhronosGroup/OpenVG-Registry#1]
The two sample implementation links in the OpenVG registry are 404’d.

https://www.khronos.org/registry/OpenVG/

Zip files missing:
https://www.khronos.org/registry/OpenVG/ri/openvg-1.1-ri.zip
https://www.khronos.org/registry/OpenVG/ri/openvg-1_0_1-ri.zip

**Comment by oddhack** [comment]
The files are definitely there in the Github repository that's supposed to be backing the webserver. Could you verify that the cloned repo on the server is correctly pulling the Github content? I stared at them quite a while looking for typos in the links but can't see them (which doesn't mean they're not there).

**Comment by oddhack** [comment]
N.b. I'm not getting back home from the F2F for about 2 more days so if you see an easy fix requiring an update to the index file, please just go ahead and commit it, or approve your own PR.

**Comment by KhronosWebservices** [comment]
Github repo has zip files in expected location. Clone on server was corrupt.  Fixed.
