### ISSUE TITLE
OpenVG Reference Implementation links broken

### ISSUE THREAD

**Issue by kphillisjr** [KhronosGroup/OpenVG-Registry#2]
The OpenVG 1.0, and OpenVG 1.1 reference Implementation links are broken on the main Khronos website.

Source URL: https://www.khronos.org/registry/OpenVG/

Effected Links:
OpenVG 1.1 Sample Implementation: 
https://www.khronos.org/registry/OpenVG/ri/openvg-1.1-ri.zip

OpenVG 1.0.1 Sample Implementation: 
https://www.khronos.org/registry/OpenVG/ri/openvg-1_0_1-ri.zip

**Comment by oddhack** [comment]
I'm not sure what's up here. The files are definitely in the repository, and AFAICT the webserver is pulling the master branch at HEAD, but the binaries aren't showing up in the webserver's local copy. I'll have to ask our webmaster to diagnose this. Thanks for the heads-up!

**Comment by KhronosWebservices** [comment]
We've had this once before. The two zip files disappear from our clone and we get `missing blob` and `error: unable to read sha1 file of ri/openvg-1.1-ri.zip` 

So far, recloning has been the only fix to resolve this issue. We are looking into why this might happen. For now, all is fixed.

**Comment by oddhack** [comment]
@Khronoswebmaster - this is happening again (404 errors on the links @kphillisjr posted above).

**Comment by oddhack** [comment]
Turns out that a virus scanner on the Khronos webserver mistakenly thought the zip files were dangerous and removed them. They've been whitelisted and this (should) not happen again.
