### ISSUE TITLE
OpenVG Conformance Tests?

### ISSUE THREAD

**Issue by kphillisjr** [KhronosGroup/OpenVG-Registry#3]
I am wondering if there is any plans to open source the conformance Test Suite for OpenVG. I know the specification for this has not changed in several years, and that since the specification was released the conformance test suite for OpenGL, OpenGL ES, and Vulcan has been open sourced (see: https://github.com/KhronosGroup/VK-GL-CTS ).

**Comment by hwan-ajou** [comment]
Finally, we opened! 
Please check OpenVG-CTS project.
